# Generated by Django 4.0.4 on 2022-05-18 11:02

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('date_of_event', models.DateField(verbose_name='Дата проведения')),
            ],
            options={
                'verbose_name': 'Тематический выпуск',
                'verbose_name_plural': 'Тематический выпуск',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('file', models.FileField(upload_to='release/', verbose_name='Документ')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='release.release', verbose_name='Тематический выпуск')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документ',
            },
        ),
    ]
