# Generated by Django 4.0.4 on 2022-05-19 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='release.release', verbose_name='Тематический выпуск'),
        ),
    ]
