# Generated by Django 4.0.4 on 2022-04-26 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Порядок вывода'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='аrea',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Порядок вывода'),
            preserve_default=False,
        ),
    ]
