# Generated by Django 4.0.4 on 2022-04-29 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_partner_order_аrea_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner', to='partners.аrea', verbose_name='Область дейстельности'),
        ),
    ]
