# Generated by Django 4.0.4 on 2022-04-23 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationalprogram',
            options={'verbose_name': 'Образовательная программа', 'verbose_name_plural': 'Образовательная программа'},
        ),
        migrations.CreateModel(
            name='UserEducationalProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed', models.BooleanField(verbose_name='Опрос пройден?')),
                ('educational_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.educationalprogram', verbose_name='Образовательная программа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участник',
            },
        ),
    ]
