# Generated by Django 4.0.4 on 2022-04-23 14:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_alter_educationalprogram_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usereducationalprogram',
            name='passed',
        ),
        migrations.AddField(
            model_name='usereducationalprogram',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания учетной записи'),
        ),
    ]
