# Generated by Django 4.0.4 on 2022-05-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('url', models.URLField(verbose_name='Ссылка')),
                ('type', models.CharField(choices=[('book', 'Книжный вариант'), ('elec', 'Электронный вариант')], max_length=50, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Библиотека качества',
                'verbose_name_plural': 'Библиотека качества',
            },
        ),
    ]
