# Generated by Django 4.0.4 on 2022-05-29 14:13

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0002_qualitylibrary'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('image_before', models.ImageField(upload_to='', verbose_name='Картинка до')),
                ('image_after', models.ImageField(upload_to='', verbose_name='Картинка после')),
                ('date_of_the_event', models.DateTimeField(verbose_name='Дата проведения')),
            ],
            options={
                'verbose_name': 'Наши проекты',
                'verbose_name_plural': 'Наши проекты',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('file', models.FileField(upload_to='our_projects/', verbose_name='Документ')),
                ('our_projects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='our_projects', to='reference.ourprojects', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документ',
            },
        ),
    ]
