# Generated by Django 4.0.4 on 2022-05-29 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0003_ourprojects_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='our_projects',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='reference.ourprojects', verbose_name='Проект'),
        ),
    ]
