# Generated by Django 4.0.4 on 2022-05-29 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_feedbackuserbusinessgames'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackuserbusinessgames',
            name='user_business_games',
        ),
        migrations.AddField(
            model_name='feedbackuserbusinessgames',
            name='business_games',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='business.businessgames', verbose_name='Деловая игра'),
            preserve_default=False,
        ),
    ]
