# Generated by Django 4.0.4 on 2022-04-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(default=1, max_length=25, verbose_name='Должность'),
            preserve_default=False,
        ),
    ]
