# Generated by Django 4.0.4 on 2022-04-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_employee_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(max_length=70, verbose_name='Должность'),
        ),
    ]
