# Generated by Django 4.0.4 on 2022-05-12 18:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionsFromGuests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=45, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=45, null=True, verbose_name='Отчество')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('phone', models.CharField(max_length=25, verbose_name='Номер телефона')),
                ('text', models.TextField(verbose_name='Комментарий')),
                ('date_created', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Дата отправки')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратная связь',
            },
        ),
    ]
